version: '3.7'

services:
  minio:
      image: minio/minio:latest
      restart: always
      entrypoint: sh
      ports:
          - 10000:9000
          - 10001:9001
      environment:
          MINIO_ROOT_USER: "root"
          MINIO_ROOT_PASSWORD: "rootpass"
          MINIO_BROWSER_REDIRECT_URL:  http://localhost:9001
      entrypoint:
          bash -c 'mkdir -p /data/repository && /opt/bin/minio server /data --console-address ":9001"'
      volumes:
          - ./s3-data:/data
      healthcheck:
          test: ["CMD", "curl", "-f", "http://localhost:9001/minio/health/live"]
          interval: 30s
          timeout: 20s
          retries: 3

