name: Build distributables and update docs

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install node modules
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Auto commit build artefacts
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: master
          commit_message: Update distributables and documentation